services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1

  frontend:
      build:
        context: ./frontend
      volumes:
        - ./frontend:/app
        - /app/node_modules
      ports:
        - "5173:5173"
      stdin_open: true
      tty: true
      environment:
        - CHOKIDAR_USEPOLLING=true
        - WATCHPACK_POLLING=true